spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fleetpulse_db
    username: postgres
    password: postgrespassword

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true 
    properties:
      hibernate:
        format_sql: true